### ISSUE TITLE
"Guru meditation" error

### ISSUE THREAD

**Issue by lawgamer** [poliva/pyqtggpo#13]
Sorry if this is a wrong place to report such errors. "Guru meditation" happens when I try to connect with another player. The error occurs randomly: 10 times in a row I've tried to play with my friend - 3 attempts were successful. Here's a log:

FB Alpha v0.2.96.74 fatal exception report (Sat Jan 31 14:48:43 2015)

----------------------------------------------------------------------
Exception 0xC0000005 (EXCEPTION_ACCESS_VIOLATION) thrown.
EIP: 0x76FB
 (attempting to read address 0x041C0004)

EAX: 0x00000000, EBX: 0x041C0000, ECX: 0x00D6423A, EDX: 0x00000000
ESI: 0x0000007F, EDI: 0x0000001C, ESP: 0x0018FC4C, EBP: 0x0018FC5C

----------------------------------------------------------------------
System information:

OS:  Microsoft Windows XP Professional Service Pack 3 (build 2600)
CPU: GenuineIntel, Pentium III Xeon "Cascades"
     2993 MHz, MMX, SSE, SSE2 (4 system processors)

Physical RAM: 1048575 KB (1023 MB) total, 1048575 KB (1023 MB) avail
Total RAM:    2097151 KB (2047 MB) total, 1048575 KB (1023 MB) avail
FB Alpha:       53132 KB in use (57284 KB peak, 141680 KB virtual)

Installed displays and display adapters:
    Generic PnP Monitor on NVIDIA GeForce GTX 560  (primary)

----------------------------------------------------------------------
FB Alpha information:

Built on May 12 2008, 20:05:36, using Visual C++ 9.0.
    Optimised for i686 CPUs.
    Using multi-byte characters for all text, active codepage is 1251.
    Debug functionality absent.

MMX optimisations enabled.
A68K emulation core enabled for MC68000 emulation.
Musashi emulation core enabled for MC68010/MC68EC020 emulation.
Doze emulation core enabled for Z80 emulation.

Emulating fatfursp (Fatal Fury Special (set 1))
    Vertical refresh is 60.00 Hz.
    CPU running at 100% of normal frequency.

Video settings:
    Selected module:    DirectDraw7 / Direct3D7 Enhanced video output
    Interface settings: Running in windowed mode, 912Ч672, 32bpp
                        Source image 304Ч224, 15bpp
    Module settings:    Using Blt() to transfer the image
                        Using Direct3D texture management

Audio settings:
    Selected module:    DirectSound3 audio output
    Interface settings: Playback at 22050Hz, 100% volume
    Module settings:    Audio is delayed by approx. 83ms

Input settings:
    Selected module:    DirectInput7 input
    Interface settings: keyboard 0 System keyboard: Клавиатура
                        mouse    0 System mouse: Мышь
                        joystick 0 MadCatz FightStick Neo (Arcade Stic

Profiling settings:
    Interface settings: Profiling module not initialised

----------------------------------------------------------------------
Detailed process information about ggpofba-ng.exe:

ggpofba-ng.exe (base address 0x00400000, size 8876 KB)

Exception occurred in module ntdll.dll:
               ntdll.dll (base address 0x76F60000, size   1536 KB)

Modules loaded by ggpofba-ng.exe:
               ntdll.dll (base address 0x76F60000, size   1536 KB)
            kernel32.dll (base address 0x74FD0000, size   1024 KB)
          KERNELBASE.dll (base address 0x76610000, size    280 KB)
              USER32.dll (base address 0x74CB0000, size   1024 KB)
               GDI32.dll (base address 0x74F40000, size    576 KB)
                 LPK.dll (base address 0x74B30000, size     40 KB)
               USP10.dll (base address 0x76430000, size    628 KB)
              msvcrt.dll (base address 0x74E90000, size    688 KB)
            ADVAPI32.dll (base address 0x76660000, size    640 KB)
             sechost.dll (base address 0x75D50000, size    100 KB)
              RPCRT4.dll (base address 0x76520000, size    960 KB)
             SspiCli.dll (base address 0x74AD0000, size    384 KB)
           CRYPTBASE.dll (base address 0x74AC0000, size     48 KB)
            COMDLG32.dll (base address 0x74DB0000, size    492 KB)
             SHLWAPI.dll (base address 0x75E00000, size    348 KB)
            COMCTL32.dll (base address 0x713A0000, size   1656 KB)
             SHELL32.dll (base address 0x750D0000, size  12580 KB)
               WINMM.dll (base address 0x70AE0000, size    200 KB)
                d3d9.dll (base address 0x72310000, size   1804 KB)
             VERSION.dll (base address 0x72A60000, size     36 KB)
             d3d8thk.dll (base address 0x73D10000, size     24 KB)
              dwmapi.dll (base address 0x70AC0000, size     76 KB)
               DDRAW.dll (base address 0x6EA20000, size    924 KB)
            DCIMAN32.dll (base address 0x74540000, size     24 KB)
            SETUPAPI.dll (base address 0x76160000, size   1652 KB)
            CFGMGR32.dll (base address 0x74C80000, size    156 KB)
            OLEAUT32.dll (base address 0x75F70000, size    572 KB)
               ole32.dll (base address 0x76000000, size   1392 KB)
              DEVOBJ.dll (base address 0x76A40000, size     72 KB)
              DSOUND.dll (base address 0x6C100000, size    456 KB)
            POWRPROF.dll (base address 0x71230000, size    148 KB)
              DINPUT.dll (base address 0x71070000, size    148 KB)
      kailleraclient.dll (base address 0x10000000, size     92 KB)
              WS2_32.dll (base address 0x763F0000, size    212 KB)
                 NSI.dll (base address 0x00020000, size     24 KB)
             ggponet.dll (base address 0x00D20000, size  53544 KB)
             apphelp.dll (base address 0x71A60000, size    300 KB)
            AcLayers.dll (base address 0x663B0000, size    560 KB)
             USERENV.dll (base address 0x71750000, size     92 KB)
             profapi.dll (base address 0x71AF0000, size     44 KB)
            WINSPOOL.DRV (base address 0x725C0000, size    324 KB)
                 MPR.dll (base address 0x722F0000, size     72 KB)
            AcGenral.DLL (base address 0x660F0000, size   2144 KB)
             UxTheme.dll (base address 0x71310000, size    512 KB)
              samcli.dll (base address 0x66520000, size     60 KB)
             MSACM32.dll (base address 0x71540000, size     80 KB)
                 sfc.dll (base address 0x68170000, size     12 KB)
              sfc_os.DLL (base address 0x66510000, size     52 KB)
              urlmon.dll (base address 0x76900000, size   1236 KB)
             CRYPT32.dll (base address 0x74B40000, size   1136 KB)
              MSASN1.dll (base address 0x74C60000, size     48 KB)
            iertutil.dll (base address 0x76700000, size   2020 KB)
            AcXtrnal.DLL (base address 0x65610000, size   2404 KB)
            SHUNIMPL.DLL (base address 0x74000000, size     24 KB)
    SortServer2003Compat.dll (base address 0x73C10000, size     52 KB)
               IMM32.DLL (base address 0x76390000, size    384 KB)
               MSCTF.dll (base address 0x75E90000, size    816 KB)
            RICHED32.DLL (base address 0x72A20000, size     24 KB)
            RICHED20.dll (base address 0x6AC10000, size    472 KB)
             mswsock.dll (base address 0x71C70000, size    240 KB)
            wshtcpip.dll (base address 0x71B00000, size     20 KB)
           snxBorder.dll (base address 0x64D00000, size    156 KB)
          snxPlugins.DLL (base address 0x64D80000, size    164 KB)
                 HID.DLL (base address 0x71AB0000, size     36 KB)
            WINTRUST.dll (base address 0x75E60000, size    180 KB)
             CLBCatQ.DLL (base address 0x76300000, size    524 KB)
            MMDevApi.dll (base address 0x72680000, size    228 KB)
             PROPSYS.dll (base address 0x6C650000, size    980 KB)
            AUDIOSES.DLL (base address 0x744C0000, size    216 KB)
            D3DIM700.DLL (base address 0x66440000, size    816 KB)
              NLAapi.dll (base address 0x71CB0000, size     64 KB)
              DNSAPI.dll (base address 0x71C20000, size    272 KB)
              winrnr.dll (base address 0x71C10000, size     32 KB)
             napinsp.dll (base address 0x71C00000, size     64 KB)
             pnrpnsp.dll (base address 0x71BE0000, size     72 KB)
             WLIDNSP.DLL (base address 0x71BB0000, size    156 KB)
               PSAPI.DLL (base address 0x74C70000, size     20 KB)
            IPHLPAPI.DLL (base address 0x729F0000, size    112 KB)
              WINNSI.DLL (base address 0x729E0000, size     28 KB)
            fwpuclnt.dll (base address 0x71B40000, size    224 KB)
            rasadhlp.dll (base address 0x71B30000, size     24 KB)
             nvd3dum.dll (base address 0x68CA0000, size  15040 KB)
                avrt.dll (base address 0x73240000, size     28 KB)

----------------------------------------------------------------------

**Comment by poliva** [comment]
Sorry, this is something to do with ggpofba. Can't fix it in fightcade at the moment.
