### ISSUE TITLE
Issue with updated sfiiin/sfiii2n savestates

### ISSUE THREAD

**Issue by Geckoin1** [poliva/pyqtggpo#14]
I tried this with one other player. We're about to load up sfiii2n game, and we started off with a black screen with character select music playing in the background. The host have to press F3 to get everything normal again. We haven't tried sfiiin yet, but I bet it's the exact same issue. This also happens offline as well.

**Comment by poliva** [comment]
Wrong repo, please follow up here:
https://github.com/poliva/fightcadestates/issues/21
