### ISSUE TITLE
Unable to edit controls in Wine

### ISSUE THREAD

**Issue by hanasu** [poliva/pyqtggpo#15]
User posted on the savestate repository:

"Hi, I like fightcade a lot and used it when I owned a PC, but now that I have a Mac, I have a problem. I want to use a controller, but I can't get the game to change controller settings through Wine. Is this just user error or something more?"

**Comment by poliva** [comment]
you probably need to install a driver for your controller, for example to get my XBox 360 Madcatz Fightstick Pro controller recognized on OS X yosemite I had to install this kernel driver: https://github.com/d235j/360Controller 

Once you get the driver for your fightstick or gamepad installed, then just setup the inputs by pressing F5 with the emulator open.
