### ISSUE TITLE
Unable to log in to FightCade (pyqtggpo-0.1.8)

### ISSUE THREAD

**Issue by YuGiOhJCJ** [poliva/pyqtggpo#16]
Hello,

I am on Slackware 14.1 (32 bits) and to play to FightCade, I am using wine and the windows version of FightCade.

Now, I would like to run FightCade on my system without using wine.

That's impossible with the Linux 64 bits version available on the website (because it is 64 bits):
./fightcade 
bash: ./fightcade: cannot execute binary file: Exec format error

Here, all is normal.
Now, I download the source code: pyqtggpo-0.1.8.tar.gz.
I do:
$ tar xvf pyqtggpo-0.1.8.tar.gz
$ cd pyqtggpo-0.1.8
$ python main.py

Then I have a window where I can enter an username and a password.
But after clicking on the "Login" button, nothing happen.
Also, the "Create Account..." button goes there:
http://ggpo.net/forums/ucp.php?mode=register
(a 404 Not Found page)

I also tried to build the binary doing this:
$ make app
But after that, I don't know what to do.
I do:
$ cd build/PyQtGGPO
$ ./PyQtGGPO 
Error loading Python lib '/tmp/build/pyqtggpo-0.1.8/build/PyQtGGPO/libpython2.7.so.1.0': /tmp/build/pyqtggpo-0.1.8/build/PyQtGGPO/libpython2.7.so.1.0: cannot open shared object file: No such file or directory

It does not find the libpython2.7.so.1.0 because it is looking at the wrong place.
The correct place should be: /usr/lib/libpython2.7.so.1.0.
I don't know why I got this behavior.

Anyway, I see no instructions to build on Linux FightCade.
In the BUILD.md file I read:
"# Building on windows"
[...]
"# Building on OSX"
[...]
And the "# Building on Linux" section is not found.
So, that was just a guess to call "make app" because when I watch the content of the Makefile, it seems to be the correct way to build for Linux.

Tell me how to do please.
Thank you.
Best regards.

**Comment by poliva** [comment]
Please redownload again, we changed from binary build to source build on linux after version 0.39:
http://www.fightcade.com/download/linux
