### ISSUE TITLE
When I click on the "eye" nothing happen

### ISSUE THREAD

**Issue by YuGiOhJCJ** [poliva/pyqtggpo#17]
Hello,

I am using fightcade-linux-v039.tar.gz on Slackware 14.1 (32 bits).
I do:
$ tar xvf fightcade-linux-v039.tar.gz
$ cd FightCade
I put the roms in the ROMs directory.
$ python main.py
I log in.
I select the room (street fighter alpha 3).
Then I click on the "eye" to watch a match but nothing happen.

What I miss?

Thank you.
Best regards.

**Comment by YuGiOhJCJ** [comment]
Oh I found it is because "wine" is launched when the emulator is called by the chat client of FightCade.
In order to work correctly, I need to put my FightCade directory in : ~/.wine/drive_c.
Now, I can play.
Why the hell the windows version of the emulator is launched? No native linux version available?

**Comment by YuGiOhJCJ** [comment]
Oh, I think I understood now.
In fact, GGPO (or the ggpofba-ng.exe file) is not open source and is part of the GGPO project [1, 2].
Here, we are on the client pyqtggpo [3] project (included in FightCade [4]).
So, FightCade is not completely open source because it uses the ggpofba-ng.exe file, but a part is open source because we have the client pyqtggpo.
Yeah, I though FightCade was more than a layer over GGPO.
I thought it was a completely rewritten client and open source.
So now it's clear for me, I will always need to call wine to play.
You can close this ticket if I am right ;)

[1] http://fr.wikipedia.org/wiki/GGPO
[2] http://ggpo.net/
[3] https://github.com/poliva/pyqtggpo/
[4] http://www.fightcade.com/

**Comment by poliva** [comment]
You're right in the last comment, closing issue.

**Comment by petran79** [comment]
I have the same issue, yet even after moving Fightcade folder to Wine directory nothing happens
