### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by GreatTornadoTheSamuraiChaser** [poliva/pyqtggpo#19]
Usually, when in-game, the names of the ones playng are shown like Player1(p1) vs Player2(p2), also, pressing "t" will open the chatbox. After some errors i've reinstalled the emulator and these are not shown anymore, also i cannot use the chat anymore. Any solution?

**Comment by Exosta** [comment]
Your symptoms are typically here when FBA is configured on Directx 9. Try to select Video > Select blitter > Basic.
