### ISSUE TITLE
player list near empty!

### ISSUE THREAD

**Issue by YuGiOhJCJ** [poliva/pyqtggpo#21]
Hello,
On fightcade version 3bb6b6fcf21fbf8f17cc5e79d3cdd7bdfb4c1785 (git), on Linux 32 bits (Slackware 14.1), I do not see completely the list of players. Some of them are missing (see [1]).
But people are able to play with me, they just have to challenge me because I am not able to see them.

This is the output in the console:
`$ python main.py 
<Uncaught exception>
TypeError: invalid result type from TreeWidgetItem.__lt__()
<Uncaught exception>
TypeError: invalid result type from TreeWidgetItem.__lt__()
<Uncaught exception>
TypeError: invalid result type from TreeWidgetItem.__lt__()
<Uncaught exception>
TypeError: invalid result type from TreeWidgetItem.__lt__()
<Uncaught exception>
TypeError: invalid result type from TreeWidgetItem.__lt__()
<Uncaught exception>
TypeError: invalid result type from TreeWidgetItem.__lt__()
<Uncaught exception>
TypeError: invalid result type from TreeWidgetItem.__lt__()
<Uncaught exception>
TypeError: invalid result type from TreeWidgetItem.__lt__()
<Uncaught exception>
TypeError: invalid result type from TreeWidgetItem.__lt__()
<Uncaught exception>
TypeError: invalid result type from TreeWidgetItem.__lt__()
<Uncaught exception>
TypeError: invalid result type from TreeWidgetItem.__lt__()
QThread: Destroyed while thread is still running`

Any idea why?

Thank you.
Best regards.

[1] http://yugiohjcj.free.fr/fightcade.png

**Comment by poliva** [comment]
that commit is 26 days old, the error you point out should be fixed in recent commits. Please re-open if it's not.
