### ISSUE TITLE
request on japanese version "Wonder 3" for 3wonders

### ISSUE THREAD

**Issue by SpinalBlood** [poliva/pyqtggpo#25]
I'd like to request the following version to be present in Fightcade: 

Title: Wonder 3 (910520 Japan) 
Rom name: wonder3 (clone of 3wonders)

Reason: 

Out of the three versions supported in this finalburn, I think the japanese is the best. Apart from the language and some better visuals in attract mode (like the highscore background for Don't Pull) there are some gameplay differences:

Roosters:
- midboss 1 throws more fireball
- endboss 1 is more aggressive
- some platforms at the end of stage 2 will crumble
- endboss 3 fireball come out with more trickier way/timing (less blatant)

Chariot:
- level 2 enemy blocks when hit relelase mini rocks, making it actually challenging since the block doesn't fire projectiles on its own (in the world version the enemy just disappears)

(there might actually be some more that I didn't notice but I finished both versions and I don't remember of for now)

These differences in the japan version would make the games more interesting, in terms of new features and balancing; in particular Roosters overral is, imho, already too easy.

To avoid confusion the "etc"(world) version should be considered obsolete and removed; although harsh I would consider this version a kind of beta. 

Thanks

**Comment by SpinalBlood** [comment]
Apparently the game doesn't desync.

Here is the savestate:

http://www.gigasize.com/get/wzm35h1gq6c

**Comment by poliva** [comment]
Added. Should be live in the next server restart.

Please next time use the savestates repository instead of the client repository: https://github.com/poliva/fightcadestates/issues
