### ISSUE TITLE
client don't start (archlinux 64 bit)

### ISSUE THREAD

**Issue by quandasim** [poliva/pyqtggpo#28]
hello
i downloaded fightcade from oficial web page.
i ran linux-install.sh and then fightcade executable, but nothing happened (no error mesage in terminal)
main.py gived me some strange errors so i googled litlle and then installed some aditional dependencies:
sudo pacman -S extra/python2-sip extra/python2-pyqt4 multilib/lib32-mpg123
now fightacade stil don't run (no error message) and main.py give me this error:

[quandasim@magi fightcade]$ ./main.py 
Traceback (most recent call last):
  File "./main.py", line 20, in <module>
    from ggpo.gui.ggpowindow import GGPOWindow
  File "/home/quandasim/games/fightcade/ggpo/gui/ggpowindow.py", line 13, in <module>
    import ggpo.common.sound
  File "/home/quandasim/games/fightcade/ggpo/common/sound.py", line 136, in <module>
    _backend = PhononBackend()
  File "/home/quandasim/games/fightcade/ggpo/common/sound.py", line 109, in __init__
    audioOutput = Phonon.AudioOutput(Phonon.MusicCategory, self)
TypeError: arguments did not match any overloaded call:
  Phonon.AudioOutput(Phonon.Category, QObject parent=None): argument 2 has unexpected type 'PhononBackend'
  Phonon.AudioOutput(QObject parent=None): argument 1 has unexpected type 'Category'
[quandasim@magi fightcade]$ 

please help i wana play samurai shodown 4 online;)

**Comment by poliva** [comment]
Arch linux comes with python3 by default, fightcade uses python2.
Running ./fightcade on FightCade's folder should detect python2 path on your arch-linux installation and use it instead of python3.

**Comment by quandasim** [comment]
hello thanks for quick reply, unfortunately i'm stil unable to  run the program.
i tried change symlink in /usr/bin from:
ls -l python
lrwxrwxrwx 1 root root 7 Mar 25 18:30 python -> python3
to:
ls -l python
lrwxrwxrwx 1 root root 7 Aug  4 18:50 python -> python2
but still fightcade shell script dont give me any error msg and the program dont run:
[quandasim@magi fightcade]$ ./fightcade
[quandasim@magi fightcade]$ 

[quandasim@magi scripts]$ ./shell-functions.sh
[quandasim@magi scripts]$ 

[quandasim@magi ~]$ python -V 2>&1 |grep "^Python 2\."
Python 2.7.10
[quandasim@magi ~]$ 

any idea whats is wrong?

**Comment by quandasim** [comment]
i asked below this youtube video:
https://www.youtube.com/watch?v=Vse9QXMy0Rk
and jose pa sugested to comment out lines 135 and 136 in /FightCade/ggpo/common/sound.py with # 
now everything works;)
