### ISSUE TITLE
ROMs are not loading

### ISSUE THREAD

**Issue by SunlightNomad** [poliva/pyqtggpo#29]
In ver. 0.42 none of my games will load up when i challenge or am challenged by someone. Clicking on my own username in the lobby used to bring up the game so i could play solo but it no longer does it. I have tried using the 'Locate ROMs Folder' but it still does not load. I have also tried moving the ROMs into a new folder but it still does not work

**Comment by BarcoPirata** [comment]
Hi!, I have the same problem. Please help us!

**Comment by tosio** [comment]
I also encountered the same problem, the game wouldn't launch when using challenging or being challenged by someone or by using the '/play' command. The client just answers with 'Lanching [whatever game should run]" but the emulator won't launch.

Executing the emulator directly from ggpofba.exe and running the rom is fine.

Using Windows 7 x64.

**Comment by poliva** [comment]
Looks like your anti-virus is blocking ggpofba or any of its components (ggpofba-ng , ggponet.dll). Please disable anti-virus and re-download fightcade.

**Comment by SunlightNomad** [comment]
Just tried your suggestion and turned off the anti virus, but it still shows  'Lanching [whatever game should run]"  I am on Windows 10

**Comment by tosio** [comment]
I don't run with an antivirus, so I doubt it would be that. In any case i also added these exceptions to my firewall, to no avail.
