### ISSUE TITLE
Game windows doesn't show up...

### ISSUE THREAD

**Issue by realmadsy** [poliva/pyqtggpo#31]
Hello. 
I'm using Fightcade on my Macbook 15 with retina display, and I'm using dual monitor.
I've been watching others' game on my second monitor. It worked perfectly.
I brought my macbook somewhere else without my monitor, that means I unplugged the second monitor.
Now, here's the thing. I ran Fightcade. It showed up right on the screen. I clicked someone's ID so I can see the game. The game windows(it says its name is 'Wine') didn't show up on the screen, but I could hear the gaming sound which means it's loaded properly, but on the dual monitor which was not even connected to my macbook. For the same reason, I couldn't play game with other people, either. 

I really want you to make the game window(Wine) shows up on where it used to be on next version of Fightcade.

Thanks for reading. Looking forward to the next update!

**Comment by poliva** [comment]
Hi,

Been able to reproduce the exact problem you mention attaching a second monitor to a MAC, however there seems to be nothing i can do in fightcade programatically to fix this. This seems to be a OSX window handling bug (it remembers the position where the window was last time it was closed, and tries to put the emulator there even if the 2nd monitor is not attached anymore).
