### ISSUE TITLE
Please add an option for setting multiple input for the same action

### ISSUE THREAD

**Issue by LinkTree3** [poliva/pyqtggpo#32]
I think it would be a good idea to be able to control the player movement using both the d-pad of a controller as well as it's analog stick at the same time.

**Comment by poliva** [comment]
It's a specific FBA setting, nothing i can do in fightcade client or server to fix that.

I can't find it right now but if i recall correctly there was a software that allowed you to use both at the same time on windows (somebody tweeted about this a while ago).
