### ISSUE TITLE
Cannot connect to other players or spectate or watch replays

### ISSUE THREAD

**Issue by apathy27** [poliva/pyqtggpo#35]
hi ive been using Fightcade for some months now and all of a sudden i just can't connect to other players, nor spectate neither watch any of the replayes. I'm using a phone adsl connections and when these connection problems occurred the phone line had gotten noisy. I then had it repaired and now there's no static on the Lanline but the same above problem occurs. I've tried restarting my router, all my ports are forwarded, even tried reinstalling fightcade but still nothing works. i can just login to fightcade and see other players in the game lobbies and play single player.

**Comment by poliva** [comment]
try running fightcade on a different computer on the same network, to see if it's a problem isolated to your computer (it works on the other computer) or to your network connection (it doesn't work on the other computer).

**Comment by apathy27** [comment]
hey i checked on a differnet computer on the same network and yeah it works..looks like a problem with my system...what can i do to fix this??
