### ISSUE TITLE
Turning off Anti Virus still doesn't allow me to load roms

### ISSUE THREAD

**Issue by SunlightNomad** [poliva/pyqtggpo#36]
In ver. 0.42 none of my games will load up when i challenge or am challenged by someone. Clicking on my own username in the lobby used to bring up the game so i could play solo but it no longer does it. I have tried using the 'Locate ROMs Folder' but it still does not load. I have also tried moving the ROMs into a new folder but it still does not work. I've disabled antivirus and firewall to redownload fightcade but the problem still persists. I am on Windows 10

**Comment by tosio** [comment]
In ver. 0.42 I also can not start any roms. I don't use antivirus, I created the exceptions in my firewall for the FBA and fightcade, and also checked if I'm using the complete rom set. I downloaded the same rom some friends are using, to no avail. Executing ggpofba directly does let me play offline, however I can't challenge or be challenge, or play online through '/play', it just stays stuck in 'starting [rom name]'

**Comment by ZelphirKaltstahl** [comment]
It's stated on the official website somewhere, that you don't need to port-forward for fightcade. FYI. So that should really not be an issue. Also I didn't port-forward in my router as I usually have to for games and it's running fine on one of my distros. However I also experience this problem when I am using my current distro. Must be some dependency or something.

**Comment by tosio** [comment]
I didn't mention port forwarding, nor is it the issue at hand. The rom itself won't load, it just stays stuck at 'starting [rom name]', when running from the fightcade client. however I CAN run the rom from ggpofba.exe so I don't think it's a problem in the rom set.

**Comment by poliva** [comment]
Open ggpofba (without starting any game), enable sound: In the sound menu, make sure the option 22050Hz is marked. Close ggpofba. Done.
