### ISSUE TITLE
Cannot connect to other players, spectate or watch replays only on my PC

### ISSUE THREAD

**Issue by apathy27** [poliva/pyqtggpo#37]
a couple of months back i've benn unable to connect to other players nore spectate or watch any replays it just shows a black screen. I can log in to Fightcade, view the lobby and see other players in the list and also play offline. i tried restarting my router, PC, reinstalling Fightcade nothing works..but on the same network via wifi i don't have these issues on my dads laptop...i can connect, spectate & watch replays, so my network is fine its just my PC..my ports are forwarded too on my PC...Please if anyone can help me out that be great.

**Comment by BlAzEdD0NuTs** [comment]
this problem has just happened to me a day ago and i can't connect to anyone, but everything else works fine offline. i can't spectate or watch replays. can someone please help out with this?

**Comment by apathy27** [comment]
solved it...i did a fresh install deleting the config files in Users>(My name) folder and reinstalled it and avoided using the whole old "config" folder i backed up with my custom button maps and only copied the "games" folder in "config" folder from my backed up files..
