### ISSUE TITLE
  FBA launches only when I close Fightcade (Ubuntu 15.10 x64)

### ISSUE THREAD

**Issue by petran79** [poliva/pyqtggpo#38]
After the command "sudo rm -rf ~/fightcade* ~/ggpo*.ini /home/petros/fightcade* /home/petros/ggpo*.ini"
FBA  client launched fine the first time and it displayed the match while FG was active. 

But now FBA refuses to launch when Fightcade client is open no matter how many seconds pass.
I have to close Fightcade and then FBA launches after 30 seconds and actual match is displayed normally.

If I click the eye icon 3 times on Fightcade and quit, FBA Alpha launches the match 3 consecutive times

**Comment by poliva** [comment]
Cannot reproduce the issue. Make sure you don't have any stalled wine process or something. Please reopen if you have any more feedback.
