### ISSUE TITLE
Can't connect to fightcade.com when logging in

### ISSUE THREAD

**Issue by vandersonmota** [poliva/pyqtggpo#41]
Hi guy, i've enabled the ports from 6000-7000 TCP/UDP and still can't login. 
I've tried with the current master branch and the latest stable and got the same error.

Edit: i'm using Linux mint 17

Any thoughts?

Thanks!

**Comment by ZelphirKaltstahl** [comment]
It's not necessary to open any ports according to the fightcade website: http://www.fightcade.com/#play
I don't have a solution though.

**Comment by poliva** [comment]
Any suspicious entry in your `/etc/hosts` file? some fightcade clones modify that file and break fightcade

**Comment by vandersonmota** [comment]
@poliva not at all

**Comment by hanasu** [comment]
I'm able to replicate this in a quick test with Cinnamon 17.2. Will try to look into it more deeply.

**Comment by poliva** [comment]
Were you able to find the problem? Closing issue. Please reopen if you have more feedback.
