### ISSUE TITLE
Mac version instantly closes as soon as it's opened

### ISSUE THREAD

**Issue by HarStuart** [poliva/pyqtggpo#43]
As soon as I open the Mac version of Fightcade, the program closes before any windows actually show up. It appears in the top bar and in the currently-running programs list of force quit, but no windows shows up and it closes itself a second later, all without displaying any error message. Running the Fightcade terminal launcher inside of the MacOS file in Package contents outputs this - the route to the program, then the Exit. Is this somehow related? Deleting and redownloading the program also has no effect. Any help is appreciated, thanks!

**Comment by poliva** [comment]
Not sure if related, but try this:

System Preferences -> Security & Privacy -> General -> Allow apps from: Mac App store and identified developers
https://pbs.twimg.com/media/CXuN1NwWAAAIgIN.jpg:large

If that doesn't work, try starting FightCade from a Terminal: /Applications/FightCade.app/Contents/MacOS/fightcade

**Comment by HarStuart** [comment]
have done both - neither worked

**Comment by poliva** [comment]
make sure it is installed in /Applications
