### ISSUE TITLE
CONNECTING TO THE SERVER

### ISSUE THREAD

**Issue by Skyway666** [poliva/pyqtggpo#45]
I used to be able to play perfectly, but after some time the game stoped working, and when i try to fight somene the screems says connecting to the server forever. I don't know what to do, and it's not about ping or internet, i can't play with anybody and i can't even expectate games. Please help me :)

**Comment by poliva** [comment]
Open ggpofba (without starting any game), enable sound: In the sound menu, make sure the option 22050Hz is marked. Close ggpofba. Done.

**Comment by Skyway666** [comment]
YOU ARE A GOD!!!!


2016-01-05 13:50 GMT+01:00 Pau Oliva <notifications@github.com>:
