### ISSUE TITLE
Multiple keypresses give unexpected result

### ISSUE THREAD

**Issue by urgh** [poliva/pyqtggpo#49]
When I have left-down-right all depressed I want the input result to be 
>000
>0x0
>010

instead of the current

>000
>0x0
>101

What can I do to change this behavior? Haven't found anything useful in ini files so far.

**Comment by poliva** [comment]
This issue si in the ggpofba emulator that fightcade uses, inherited from GGPO. Unfortunately not something we can easily fix at the moment.
