### ISSUE TITLE
Build not successful, missing file ggposcriptsruntimehook.py

### ISSUE THREAD

**Issue by Garrin** [poliva/pyqtggpo#7]
Ok this is what I tried:

1. Create a virtualenv in the project folder using this command: **virtualenv -p python2.7 pyqtggpo-master**
2. cd pyqtggpo-master
3. **bin/pip2.7 install geoip2**
4. **bin/pip2.7 install pyinstaller**
5. **bin/pyinstaller -w -i ggpo\resources\img\icon.ico -n pyqtggpo --runtime-hook ggpo\scripts\runtimehook.py main.py**

Everything works fine except the last step, which gives me the following output:

xiaolong @ xiaolong-VPCF13J0E  ~/Applications/pyqtggpo-master
└─ $ ▶ **bin/pyinstaller -w -i ggpo\resources\img\icon.ico -n pyqtggpo --runtime-hook ggpo\scripts\runtimehook.py main.py**
7 INFO: wrote /home/xiaolong/Applications/pyqtggpo-master/pyqtggpo.spec
56 INFO: UPX is not available.
74 INFO: Processing hook hook-os
176 INFO: Processing hook hook-time
179 INFO: Processing hook hook-cPickle
252 INFO: Processing hook hook-_sre
356 INFO: Processing hook hook-cStringIO
422 INFO: Processing hook hook-encodings
431 INFO: Processing hook hook-codecs
1039 INFO: Extending PYTHONPATH with /home/xiaolong/Applications
1039 INFO: checking Analysis
1039 INFO: building Analysis because out00-Analysis.toc non existent
1039 INFO: running Analysis out00-Analysis.toc
1089 INFO: Analyzing /home/xiaolong/Applications/pyqtggpo-master/local/lib/python2.7/site-packages/PyInstaller/loader/_pyi_bootstrap.py
1103 INFO: Processing hook hook-os
1116 INFO: Processing hook hook-site
1125 INFO: Processing hook hook-encodings
1190 INFO: Processing hook hook-time
1191 INFO: Processing hook hook-cPickle
1248 INFO: Processing hook hook-_sre
1336 INFO: Processing hook hook-cStringIO
1407 INFO: Processing hook hook-codecs
1763 INFO: Processing hook hook-pydoc
1933 INFO: Processing hook hook-email
1974 INFO: Processing hook hook-httplib
2026 INFO: Processing hook hook-email.message
2117 INFO: Analyzing /home/xiaolong/Applications/pyqtggpo-master/local/lib/python2.7/site-packages/PyInstaller/loader/pyi_importers.py
2147 INFO: Analyzing /home/xiaolong/Applications/pyqtggpo-master/local/lib/python2.7/site-packages/PyInstaller/loader/pyi_archive.py
2170 INFO: Analyzing /home/xiaolong/Applications/pyqtggpo-master/local/lib/python2.7/site-packages/PyInstaller/loader/pyi_carchive.py
2194 INFO: Analyzing /home/xiaolong/Applications/pyqtggpo-master/local/lib/python2.7/site-packages/PyInstaller/loader/pyi_os_path.py
2197 INFO: Analyzing main.py
2290 INFO: Processing hook hook-distutils
2512 INFO: Processing hook hook-xml
2597 INFO: Processing hook hook-xml.sax
2620 INFO: Processing hook hook-pyexpat
2771 INFO: Hidden import 'codecs' has been found otherwise
2771 INFO: Hidden import 'encodings' has been found otherwise
2771 INFO: Including custom run-time hooks
2772 INFO: Looking for run-time hooks
2772 INFO: Analyzing rthook /home/xiaolong/Applications/pyqtggpo-master/ggposcriptsruntimehook.py
Traceback (most recent call last):
  File "bin/pyinstaller", line 9, in <module>
    load_entry_point('PyInstaller==2.1', 'console_scripts', 'pyinstaller')()
  File "/home/xiaolong/Applications/pyqtggpo-master/local/lib/python2.7/site-packages/PyInstaller/main.py", line 88, in run
    run_build(opts, spec_file, pyi_config)
  File "/home/xiaolong/Applications/pyqtggpo-master/local/lib/python2.7/site-packages/PyInstaller/main.py", line 46, in run_build
    PyInstaller.build.main(pyi_config, spec_file, **opts.__dict__)
  File "/home/xiaolong/Applications/pyqtggpo-master/local/lib/python2.7/site-packages/PyInstaller/build.py", line 1924, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/xiaolong/Applications/pyqtggpo-master/local/lib/python2.7/site-packages/PyInstaller/build.py", line 1873, in build
    execfile(spec)
  File "/home/xiaolong/Applications/pyqtggpo-master/pyqtggpo.spec", line 6, in <module>
    runtime_hooks=['ggposcriptsruntimehook.py'])
  File "/home/xiaolong/Applications/pyqtggpo-master/local/lib/python2.7/site-packages/PyInstaller/build.py", line 446, in __init__
    self.__postinit__()
  File "/home/xiaolong/Applications/pyqtggpo-master/local/lib/python2.7/site-packages/PyInstaller/build.py", line 309, in __postinit__
    self.assemble()
  File "/home/xiaolong/Applications/pyqtggpo-master/local/lib/python2.7/site-packages/PyInstaller/build.py", line 645, in assemble
    importTracker.analyze_script(hook_file)
  File "/home/xiaolong/Applications/pyqtggpo-master/local/lib/python2.7/site-packages/PyInstaller/depend/imptracker.py", line 266, in analyze_script
    stuff = open(fnm, 'rU').read() + '\n'
**IOError: [Errno 2] No such file or directory: '/home/xiaolong/Applications/pyqtggpo-master/ggposcriptsruntimehook.py'**

So it seems there is a file missing for me.

**Comment by Garrin** [comment]
Ah ok will test it with correct slashes, I didn't see that when I copied the command fromt the BUILD.md file. Maybe it's better to put in a standard version of the command (using / not \ like only on windows) ;)

**Comment by Garrin** [comment]
The pyinstall runs through now without error : )
However, after pip install geoip2 there is no mmdb file in the whole directory structure (not even on my whole partition). Can you include it or could you write a download link into the BUILD.md file? I found this: https://github.com/maxmind but I can't find that .mmdb file which I am supposed to copy into the dist folder.

**Comment by poliva** [comment]
You can get the db from here: http://dev.maxmind.com/geoip/geoip2/geolite2/
