### ISSUE TITLE
Own server

### ISSUE THREAD

**Issue by Guigo-** [poliva/pyqtggpo#8]
Hi,

it would be nice to have the opportunity to choose the server, just with a simple panel and a textbox for an URL.

Furthermore, i'm not able to find the config file where the server URL is stored. When the server has some issues, a message error says : "cannot connect fightcade.com". Even though the file ggpo.config have a line with "SERVER=ggpo.net:7000". So what is the right URL ?

**Comment by poliva** [comment]
Use papasi's pyqtggpo for that, latest version from git supports custom server.

**Comment by Guigo-** [comment]
i saw your revert on the commit "custom server" (https://github.com/poliva/pyqtggpo/commit/e635ca3f1fe95990513860d310e04627a2be0d22), did you have some reason for that ? It didn't work ?

**Comment by poliva** [comment]
it worked at the time, but I preferred to have a custom client tailored for fightcade's server.

**Comment by Guigo-** [comment]
Sorry, I don't get your point. What is preventing to have this field for custom server with a default url, your own ?
I insist on this point (sorry for that) because it will be great to let people mounting a backup server in case of your server is down (DDOS, crashed, I don't know...).
