### ISSUE TITLE
Unsupported State Switching via Menu 

### ISSUE THREAD

**Issue by OMGWTFLOL** [poliva/pyqtggpo#9]
Hello,

On pyqtggpo for GGPO there was an option to set an "unsupported state" directory and when in the unsupported room, use a menu to choose from those states to automatically switch "unsupported_ggpo.fs" to the chosen game.  Is it possible to add that feature back in? The code for it should be on the original pyqtggpo branch.

**Comment by poliva** [comment]
I reused part of the original code to sync "supported" savestates, as all the previous "unsupported" states are now supported games in fightcade. The unsupported room is still there, but most unsupported games are unsupported because they have issues or desync when playing online.
